### PR TITLE
feat: add new arch

### PR DESCRIPTION
**Pull request by WoLewicki**
## PR adding New Architecture support to the library :tada:

We at [Software Mansion](https://swmansion.com/) have been working on [improving support](https://blog.swmansion.com/sunrising-new-architecture-in-the-new-expensify-app-729d237a02f5) for the new architecture for quite a while now. If you need help with anything related to New Architecture, like:
- [migrating your library](https://x.com/swmansion/status/1717512089323864275)
- [migrating your app](https://github.com/Expensify/App/pull/13767)
- [investigating issues](https://github.com/facebook/react-native/pulls?q=sort%3Aupdated-desc+is%3Apr+author%3Aj-piasecki+is%3Aopen)
- [improving performance](https://x.com/BBloniarz_/status/1808138585528303977)

or you just want to ask any questions, hit us up on [projects@swmansion.com](mailto:projects@swmansion.com)

---

This PR:

- upgrades Example app to newest RN version and adds code for testing the lib
- includes interoperability between the old and the new architecture

### CODE REVIEW

**Review by Polidoro-root — APPROVED** [review]
I made an upgrade RN version from my project and these changes are exactly what was needed to work on New Arch. I've spent quite some time changing mainly Objective-C code before I found this PR and tested in an existent project and a new one.

**Comment by WoLewicki** [comment]
@oguzhnatly could you take a minute and review and hopefully merge the support for new architecture? 🚀

**Review by oguzhnatly — APPROVED** [review]

**Comment by oguzhnatly** [comment]
Thanks for your PR @WoLewicki!

**Comment by WoLewicki** [comment]
Thanks! Could we get a release with this code? 😅

**Comment by WoLewicki** [comment]
Also right now do we have any files excluded from ending up in the npm package? I am curious about the `Example` app since I do not see any code excluding it from being packed.

**Pull request merged**
